### PR TITLE
Allow users to run 7.3, 7.4, or 8.0

### PR DESCRIPTION
**Pull request by svpernova09**

### CODE REVIEW

**Comment by svpernova09** [comment]
I got you some code @garak

**Comment by svpernova09** [comment]
> Good. But 7.4 is superfluous here, since "^7.3" is including every 7 minor version above 7.2

According to https://getcomposer.org/doc/articles/versions.md#caret-version-range-

Screen Shot 2020-08-10 at 16 25 14

I'm understanding this to mean our PHP versions as stated:

```php
    "require": {
        "php": "^7.3||^7.4||^8.0"
    },
```

Will be translated as `>=7.3 <7.4.0` OR `>=7.4 <7.5.0`  OR `>=8.0 <8.1.0` which will allow any patch version of 7.3, 7.4, or 8.0 PHP release.

**Comment by garak** [comment]
You didn't read it carefully

**Comment by svpernova09** [comment]
> You didn't read it carefully

This is not a helpful comment.

**Comment by garak** [comment]
Just re-read it: you took the rules for zero versions as Universal's (they aren't)

**Pull request merged**
